# site settings
title: philterSoup
subtitle: s space on the interwebz
email: sanjay.das.work@gmail.com
description: null
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.philtersoup.com" # the base hostname & protocol for your site
author:
street_address: Khar West
city: Mumbai
# state: TN
# zip_code: 55555
# country: United States of America
phone: // EMAIL ME INSTEAD! 

# homepage tiles
tiles-source: "pages" # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: http://instagram.com/philtersoupmusic/
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/philterSoup

# build settings
markdown: kramdown

sass:
  style: compressed
